# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"IPFS": "00_httpapi.ipynb"}

modules = ["httpapi.py"]

doc_url = "https://moarshy.github.io/immerse/"

git_url = "https://github.com/moarshy/immerse/tree/master/"

def custom_doc_links(name): return None
