# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_coreurl": "00_utils.ipynb",
         "parse_response": "00_utils.ipynb",
         "add_items": "01_httpapi.ipynb",
         "ls_items": "01_httpapi.ipynb",
         "get_items": "01_httpapi.ipynb",
         "cat_items": "01_httpapi.ipynb",
         "pin_add": "01_httpapi.ipynb",
         "pin_ls": "01_httpapi.ipynb",
         "pin_rm": "01_httpapi.ipynb",
         "rspin_add": "01_httpapi.ipynb",
         "rspin_ls": "01_httpapi.ipynb",
         "rspin_rm": "01_httpapi.ipynb",
         "rpin_add": "01_httpapi.ipynb",
         "rpin_ls": "01_httpapi.ipynb",
         "rpin_rm": "01_httpapi.ipynb",
         "block_get": "01_httpapi.ipynb",
         "block_put": "01_httpapi.ipynb",
         "block_rm": "01_httpapi.ipynb",
         "block_stat": "01_httpapi.ipynb",
         "mfs_chcid": "01_httpapi.ipynb",
         "mfs_cp": "01_httpapi.ipynb",
         "mfs_flush": "01_httpapi.ipynb",
         "mfs_ls": "01_httpapi.ipynb",
         "mfs_mkdir": "01_httpapi.ipynb",
         "mfs_mv": "01_httpapi.ipynb",
         "mfs_read": "01_httpapi.ipynb",
         "mfs_rm": "01_httpapi.ipynb",
         "mfs_stat": "01_httpapi.ipynb",
         "mfs_write": "01_httpapi.ipynb",
         "get_peers": "01_httpapi.ipynb",
         "dht_find_peer": "01_httpapi.ipynb",
         "dht_value_provider": "01_httpapi.ipynb",
         "dht_get_value": "01_httpapi.ipynb"}

modules = ["utils.py",
           "httpapi.py"]

doc_url = "https://moarshy.github.io/immerse/"

git_url = "https://github.com/moarshy/immerse/tree/master/"

def custom_doc_links(name): return None
