# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_coreurl": "00_httpapi.ipynb",
         "add": "00_httpapi.ipynb",
         "get": "00_httpapi.ipynb",
         "cat": "00_httpapi.ipynb",
         "get_peers": "00_httpapi.ipynb",
         "find_dht_peer": "00_httpapi.ipynb",
         "find_value_provider": "00_httpapi.ipynb",
         "get_dht_value": "00_httpapi.ipynb"}

modules = ["httpapi.py"]

doc_url = "https://moarshy.github.io/immerse/"

git_url = "https://github.com/moarshy/immerse/tree/master/"

def custom_doc_links(name): return None
